[Content]
Packages=
		dracut
		linux
		linux-firmware
		btrfs-progs
		e2fsprogs
		xfsprogs
		dosfstools
		skopeo
		dbus
		dbus-glib
		glib2
		shadow
		pacman
		ostree
		base
		polkit
		vim
		nano
		sudo
		polkit
		just
		podman
		distrobox
		less
		man
		man-db
		man-pages
		mokutil
		zram-generator
		curl
		wget
		noto-fonts
		noto-fonts-extra
		noto-fonts-cjk
		noto-fonts-emoji
		unicode-emoji
		otf-font-awesome
		pavucontrol
		wireplumber
		pipewire
		pamixer
		pipewire-pulse
		network-manager-applet
		inetutils
		net-tools
		bluez
		bluez-utils
		bluez-tools
		blueman
		usbutils
		zsh
		gtk3
		gobject-introspection
		gtk-layer-shell
