[Content]
Packages=
		lxqt-policykit
		gnome-keyring
		fastfetch
		grim
		slurp
		kitty
		thunar
		thunar-archive-plugin
		gvfs
		file-roller
		7zip
		bzip3
		unrar
		unzip
		rpmextract
		dpkg
		gnome-disk-utility
		flatpak
		bazaar
