[Content]
VolatilePackages=shim-signed
Bootloader=systemd-boot
ShimBootloader=signed

[Build]
SandboxTrees=subprojects/arch-bootc-pkgs/repo.gpg:/usr/share/pacman/keyrings/hecknt.gpg
             repos/hecknt-trusted:/usr/share/pacman/keyrings/hecknt-trusted
             repos/bootc.conf:/etc/pacman.d/bootc.conf

