[Output]
SplitArtifacts=uki,partitions
Format=disk
ManifestFormat=json

[Content]
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=amethyris_*:usr-verity=amethyris_*:usr-verity-sig=amethyris_*:root=amethyris-*:swap=amethyris-*:home=amethyris-*
        ipe.enforce=0
        apparmor=1
        lsm=landlock,lockdown,yama,integrity,apparmor,bpf
        console=tty1
InitrdProfiles=
KernelInitrdModules=default
Hostname=amethyris
RemoveFiles=
        /boot/*-ucode.img
Bootable=true


[Validation]
SecureBoot=yes
SignExpectedPcr=yes
