[Match]
Profiles=bootc
Distribution=arch

[Content]
RemoveFiles=
    /usr/etc
    /var/*
    /boot/*

Packages=
    dracut
    erofs-utils
    skopeo

VolatilePackages=bootc

[Content]
# We want to use the bootc/ostree dracut modules instead of letting mkosi handle this. Please reconsider once arbitrary content can be added to the initramfs somehow
Bootable=no
KernelCommandLine=

[Output]
OciLabels=containers.bootc=1
Format=oci
