# Display PulseAudio volume control application (both GTK and Qt varieties)
# as a floating window.

for_window [app_id="pavucontrol"] {
    floating enable
    move position center
}

for_window [app_id="pavucontrol-qt"] {
    floating enable
    move position center
}

# Polkit window
for_window [app_id="lxqt-policykit-agent"] {
	floating enable
	move position center
}

# "Save as" and similar
for_window [title="(?:Open|Save) (?:File|Folder|As)"] {
	floating enable
	resize set width 40ppt height 80ppt
}

# Copying files in thunar
for_window [app_id="thunar" title=".*Progress.*"] floating enable
for_window [app_id="thunar" title=".*Confirm.*"] floating enable
for_window [app_id="thunar" title=".*Rename.*"] floating enable
